//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientJob
    {
        public ClientJob()
        {
            this.TimeSheetDetails = new HashSet<TimeSheetDetail>();
        }
    
        public System.Guid ClientJobId { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid JobId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Job Job { get; set; }
        public virtual ICollection<TimeSheetDetail> TimeSheetDetails { get; set; }
    }
}
