//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.ClientJobs = new HashSet<ClientJob>();
        }
    
        public System.Guid JobId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ClientJob> ClientJobs { get; set; }
    }
}
