//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetDetail
    {
        public System.Guid TimeSheetId { get; set; }
        public System.Guid ClientJobId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime StopTime { get; set; }
        public System.Guid WorkCodeId { get; set; }
        public string Comments { get; set; }
        public System.Guid UnitId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual ClientJob ClientJob { get; set; }
        public virtual TimeSheetDetail TimeSheetDetail1 { get; set; }
        public virtual TimeSheetDetail TimeSheetDetail2 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual User User { get; set; }
        public virtual WorkCode WorkCode { get; set; }
    }
}
