//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TimeSheetDetails = new HashSet<TimeSheetDetail>();
            this.UserClients = new HashSet<UserClient>();
        }
    
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<TimeSheetDetail> TimeSheetDetails { get; set; }
        public virtual ICollection<UserClient> UserClients { get; set; }
    }
}
