//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClient
    {
        public System.Guid UserClientId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
